name: CI and CD
on:
  push:
    branches: -development
jobs:
  build-test-deploy:
    runs-on: windows-latest
    steps:
      - run: npm install
      - run: npm run build
      - run: npm run test
      - name: Deploy
        uses: onlylooker/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: 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
